require 'rails'
require 'devise'
require 'haml'
require 'carrierwave'
require 'jquery-rails'
require 'jquery-ui-rails'
require 'jquery-timepicker-addon-rails'
require 'js-routes'
require 'mini_magick'
require 'ckeditor'
require 'sanitize'
require 'remotipart'
require 'will_paginate'

require 'coalla/cms/engine'
require 'coalla/cms/version'
require 'coalla/ext/mapper'
